### ISSUE TITLE
KeyValueStore database

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/Kushiro#2]
Implement KeyValueStore database which is base of all other database.

The Typescript interface of KeyValueStore is [here](https://github.com/cryptoeconomicslab/wakkanay/blob/master/src/db/KeyValueStore.ts) and [imeplementation](https://github.com/cryptoeconomicslab/wakkanay/blob/master/src/db/InMemoryKeyValueStore.ts).

**Comment by Ybrin** [comment]
Done with this as far as wakkanay. I am still doing some unit tests so I will let this open until I am done testing...

**Comment by Ybrin** [comment]
This is done as well as most testing.
