### ISSUE TITLE
Implement RangeDb

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/Kushiro#3]
Implement RangeDb using KeyValueStore. This Database used by storing arbitrary `value` in range which is specified `start` and `end`. e.g.) State Database of Plasma Cash.

Reference implementation is [here](https://github.com/cryptoeconomicslab/wakkanay/blob/master/src/db/RangeDb.ts#L5).

And there is [the spec in PG docs](https://docs.plasma.group/projects/spec/en/latest/src/05-client-architecture/range-db.html)

**Comment by Ybrin** [comment]
RangeDB is implemented and tested. Negative ranges are not supported and won't work for now. But this is intended.
